### ISSUE TITLE
Catching PayPal PHP API 400 errors on localhost:8000

### ISSUE THREAD

**Issue by nickbluestone98** [anouarabdsslm/laravel-paypalpayment#111] opened 2017-05-23 08:06 UTC
The package works great! and I am taking payments perfectly! I am struggling to catch and redirect when incorrect details e.g. bank card details are entered by a user. The Laravel application just throws a 400 error.

What I am wanting to do is catch the errors and redirect back and notify the user.

The code below is where I make a request:

```
try {
    // ### Create Payment
    // Create a payment by posting to the APIService
    // using a valid ApiContext
    // The return object contains the status;

    $payment->create($this->_apiContext);

} catch (\PPConnectionException $ex) {
    return Redirect::back()->withErrors([$ex->getMessage() . PHP_EOL]);
}

dd($payment);
```

When a successful payment is made I get a nice return object that I can reference and action accordingly, when there is an issue like a 400 error it kills the application completely  and DOES NOT catch and redirect the errors back to the user.

The error code messages are:

```
PayPalConnectionException in PayPalHttpConnection.php
Got Http response code 400 when accessing 
https://api.sandbox.paypal.com/v1/payments/payment.
```

Has anyone faced similar issues ?

I know when the application isn't in dev mode I can have error pages specifically to catch certain error codes. But I really want to catch errors and redirect back to the form with notifications for the user.

Thanks in advance to any wizard who can help.

**Comment by anouarabdsslm** [comment] 2017-05-25 14:17
@nickbluestone98  check on paypal what does that error code refer to then customize the error message to your users.

**Comment by nickbluestone98** [comment] 2017-05-25 14:42
Hello @anouarabdsslm ,

I have checked the docs, the code is failing to catch errors and just throws a Laravel  400 error. I have looked around the net and found articles like this: https://stackoverflow.com/questions/33138269/laravel-paypal-payment-return-400 everything
Everything seems correct, look at my below code.

```
try {
    // ### Create Payment
    // Create a payment by posting to the APIService
    // using a valid ApiContext
    // The return object contains the status;

    $payment->create($this->_apiContext);
    
//will not catch here :(  throws Laravel 400 error !!!!!!!!!!!!!!!!
} catch (\PPConnectionException $ex) {
    return Redirect::back()->withErrors([$ex->getMessage() . PHP_EOL]);
}

//if we get an approved payment ! This fires perfectly when succesful!!!
if($payment->state == 'approved') {
    //if success we hit here fine!!!
}
```
Can you double check at your end? the API handles 400 errors for you?

Nick.

**Comment by nickbluestone98** [comment] 2017-05-30 08:39
Hello, can I nudge you on this?

Nick.

**Comment by nickbluestone98** [comment] 2017-05-30 08:41
![screen shot 2017-05-30 at 09 41 02](https://cloud.githubusercontent.com/assets/20666118/26575208/21f3d8a4-451c-11e7-9351-89f7d12e4c0f.png)

**Comment by anouarabdsslm** [comment] 2017-05-30 17:02
@nickbluestone98  sorry for delay , the issue is the exception type you are catching is not exist with the new paypal sdk , try to use `PayPalConnectionException` instead of `PPConnectionException` I will update that in the doc as well

**Comment by anouarabdsslm** [comment] 2017-05-30 17:02
@nickbluestone98  if that solve your issue let me know so i can close this issue. thanks

**Comment by binitghetiya** [comment] 2017-05-31 06:07
I got the same error.
As per my understanding error is not from Paypal but from laravel storage permission, i gave (sudo chmod 777 -R storage/) permission to storage and it works fine as per documentation.

Thanks for the library saved lots of my time :+1:

**Comment by nickbluestone98** [comment] 2017-05-31 08:35
@binitghetiya Don't really understand how the error can be related to the storage permissions, I tried anyway and it did not work.

@anouarabdsslm This different call did not work either, see below code:

```
try {
    // ### Create Payment
    // Create a payment by posting to the APIService
    // using a valid ApiContext
    // The return object contains the status;
    $payment->create($this->_apiContext);
    
} catch (\PayPalConnectionException $ex) {
    echo $ex->getCode(); // Prints the Error Code
    echo $ex->getData(); // Prints the detailed error message 
    dd($ex);
}
```
I think it has to be a small bug with way the API handles it's errors. In the `PayPalHttpConnection.php` located in the PayPal core (where the error is occurring) the `$ex` fails to throw back errors for the API to catch correctly. If I `dd($ex)` before the variable is `throw` I get a lovely response object. 

See code of response object with errors:

```
PayPalConnectionException {#250 ▼
  -url: "https://api.sandbox.paypal.com/v1/payments/payment"
  -data: "{"name":"VALIDATION_ERROR","details":[{"field":"payer.funding_instruments[0].credit_card","issue":"Credit card number is invalid for the credit card type."}],"message":"Invalid request. See details.","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#VALIDATION_ERROR","debug_id":"dfba0aeb93dec"}"
  #message: "Got Http response code 400 when accessing https://api.sandbox.paypal.com/v1/payments/payment."
  #code: 400
  #file: "/Users/nick/Sites/beattheagent/vendor/paypal/rest-api-sdk-php/lib/PayPal/Core/PayPalHttpConnection.php"
  #line: 155
  -trace: {▶}
}
```

When the code tries to `throw $ex` Laravel throws a 400 error and I cannot catch any PayPal error! See the below code as an example of the `PayPalHttpConnection.php` code, I have commented out `dd($ex);` so I can show you where it breaks so you can see for yourself.

```

//LINE 152---------------------
//More Exceptions based on HttpStatus Code
if ($httpStatus < 200 || $httpStatus >= 300) {

    $ex = new PayPalConnectionException(
        $this->httpConfig->getUrl(),
        "Got Http response code $httpStatus when accessing {$this->httpConfig->getUrl()}.",
        $httpStatus
    );

    $ex->setData($result);

    $this->logger->error("Got Http response code $httpStatus when accessing {$this->httpConfig->getUrl()}. " . $result);
    $this->logger->debug("\n\n" . str_repeat('=', 128) . "\n");

    dd($ex); //<<<<<<<< displays required errors! we want this object!!!!!! >>>>>>>>>>
    throw $ex; //DOES NOT THROW RESPONSE OBJECT CORRECTLY
}

```

Nick.

**Comment by nickbluestone98** [comment] 2017-05-31 11:55
Right guys,

It would appear that Laravel's default `Exception` method was interfering with the PayPal API `PayPalConnectionException`. So I modified the code to catch general `Exception` errors only as it contained all required error objects. The `\` before `Exception` was critical! as it needs the correct namespace (in my case anyway, your application may be different).

    try {
        // ### Create Payment
        // Create a payment by posting to the APIService
        // using a valid ApiContext
        // The return object contains the status;
        $payment->create($this->_apiContext);
        
    } catch (\Exception $ex) {
        return Redirect::back()->withErrors([$ex->getData()])->withInput(Input::all());
    }

This [link][1] was highly useful, although in my case the namespacing was out so nothing was every caught.

In my investigations I came across `app/Exceptions/Handler.php`. Here you can extend the render method to grab a `PayPalConnectionException` and handle the errors uniquely to that specific exception . See code:

    //Be sure to include the exception you want at the top of the file
    use PayPal\Exception\PayPalConnectionException;//pull in paypal error exception to work with

    public function render($request, Exception $e)
    {
        //check the specific exception
        if ($e instanceof PayPalConnectionException) {
            //return with errors and with at the form data
            return Redirect::back()->withErrors($e->getData())->withInput(Input::all());
        }
    
        return parent::render($request, $e);
    } 

Either work great, but for me it felt neater to just change the catch method to a lookout for a general `Exception`, where I am testing if a payment was successful.

Hope this helps anyone facing similar issues :D!!!

Nick.

  [1]: https://github.com/paypal/PayPal-PHP-SDK/wiki/exception-'PayPal%5CException%5CPayPalConnectionException'-with-message-'Got-Http-response-code-400-when-accessing

**Comment by binitghetiya** [comment] 2017-05-31 12:05
For more we can first catch PPException then catch parent Exception something like below right ?

```
try {
            $payment->create($this->_apiContext);
        } catch (\PPConnectionException $ex) {
            return "Exception: " . $ex->getMessage() . PHP_EOL;
            exit(1);
        } catch (\Exception $e) {
             return "Exception: " . $e->getMessage() . PHP_EOL;
            exit(1);
}

```

**Comment by nickbluestone98** [comment] 2017-05-31 12:09
@binitghetiya Try submitting incorrect card details and see how your application retrieves and handles the errors. For me `\PPConnectionException` and `PayPalConnectionException ` were always ignored and Laravel just caught using the general `\Exception` method.

**Comment by binitghetiya** [comment] 2017-05-31 12:28
@nickbluestone98  yes i got  the same problem only \Exception class will be able to catch that.
Thanks for Explanation. :+1:

**Comment by nickbluestone98** [comment] 2017-05-31 12:54
@binitghetiya No problem 👍

**Comment by anouarabdsslm** [comment] 2017-05-31 22:37
@nickbluestone98 @binitghetiya  sorry for delay guys, anyway each one handle the exceptions the way it works for his project.Good luck guys

**Closed by anouarabdsslm** 2017-05-31 22:37 UTC
